# Generated by Django 6.0.4 on 2026-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevQA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
